name: Package

on:
  - push
  - pull_request

jobs:

  sdist:
    runs-on: ubuntu-latest
    name: Build source distribution
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: List project dependencies
      run: python setup.py list_requirements
    - name: Install project dependencies
      run: python -m pip install -r requirements.txt
    - name: Build wheel distribution
      run: python setup.py sdist
    - name: Store built archive
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist/*

  wheel:
    runs-on: ubuntu-latest
    name: Build wheel distribution
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: List project dependencies
      run: python setup.py list_requirements
    - name: Install project dependencies
      run: python -m pip install -r requirements.txt
    - name: Build wheel distribution
      run: python setup.py bdist_wheel
    - name: Store built wheel
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist/*

  upload:
    environment: PyPI
    runs-on: ubuntu-latest
    name: Upload to PyPI
    if: startsWith(github.ref, 'refs/tags/v')
    needs:
    - sdist
    - wheel
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Download built distributions
      uses: actions/download-artifact@v2
      with:
          name: dist
          path: dist
    - name: Publish distributions to PyPI
      if: startsWith(github.ref, 'refs/tags/v')
      uses: pypa/gh-action-pypi-publish@release/v1

  changelog:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    name: Update GitHub release notes
    needs: upload
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Release a Changelog
      uses: rasmus-saks/release-a-changelog-action@v1.0.1
      with:
        github-token: '${{ secrets.GITHUB_TOKEN }}'

  attach:
    runs-on: ubuntu-latest
    name: Attach artifacts to GitHub release
    if: startsWith(github.ref, 'refs/tags/v')
    needs: changelog
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: List project dependencies
      run: python setup.py list_requirements
    - name: Install project dependencies
      run: python -m pip install -r requirements.txt
    - name: Build new HMM artifacts
      run: python setup.py build_data -f -r
    - name: Compress Pfam HMM
      run: gzip -c build/lib/gecco/hmmer/Pfam.h3m > Pfam.h3m.gz
    - name: Upload HMM
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: Pfam.h3m.gz
